language: node_js
node_js:
- '8.9.0'
before_script:
- npm install
script:
- npm run lint
- npm run test:unit
- npm run test:integration
deploy:
  provider: heroku
  api_key:
    secure: llK8Ps693BDYPJUWq1xHR2LntemQVyCS35s+CX64bTnZZDXV0stT/gdshPFzsLSkCK5xX4z5g8Sq4yW7PVPWoCLeS9k5f0gkrKAxWdo09TaIfrQdNkvJG72ZNF3r/QuYTQY06jek4tjenhhquuCtybT9T0Yc2yT6hdejKKGy2aB/1kr6v7xbbZdFyyP/eneMy3QJ9Cod3ngUDh9JANVgSsAAzP4NZIbBb7Up9KEhSnOb1JlRPpEubUO4vxs3YeTI9Fpk67r/WJ/Cnk8Xw9kvhcDp4kejoUuT53uqZXqoSMGC1eqsTa9sbfG52iNpo2AM9DTnipV++yxNgvuvlfq68Ksrfd99C+P2oItq+1zgEQzhNHfG80ZmqPnIlp8c3wsginqySFAaFqG1+2vC90kvFyr65ZcsQUAzaZZuygfQ3RPEkiq2bplFG4iPnSncd1OiP1IoC6It36Bwk8NBoA/6Vs7HORKtuDZeet/2TvuDgKo99MkSkUBYTJ8TJtDU5vO+LqarmVuDTtJET33qyQPKeLie3WbSHeekMrnse8Jcsxq3Uiqap4DpPA8LZS3e1M/UH6A31R4v8wF0FloboePmP3tvuTDIKEV4boqY1qsSR8qEZsI5nBtdfJJw9eIOrQXHu257wOWKmQrbVz4SJ88P2aP1LcCfwlYIPAFVPQoUv4E=
